# app
app.kafka.topic=product.a.orders

# Product A
# kafka
producta.kafka.bootstrap-servers=localhost:9092
producta.kafka.consumer-group-id=orders-management-consumer
producta.kafka.consumer-auto-offset-reset=earliest
producta.kafka.listener-ack-mode=record
producta.kafka.auto-startup=true

# database
spring.datasource.url=jdbc:postgresql://localhost:5432/ordermanagement
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=ordermanagement_user
spring.datasource.password=ordermanagement

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect